export type PricingCategoryId =
  | "branding"
  | "website-design"
  | "ecommerce"
  | "lms-platforms"
  | "brand-website-bundles";

export interface PricingPackage {
  id: string;
  category: PricingCategoryId;
  name: string;
  price: string;
  bestFor: string;
  deliverables: string[];
  revisions?: string;
  support?: string;
  thirdPartyCosts?: string;
  notes?: string[];
  cta: string;
  recommended?: boolean;
}

export interface PricingCategory {
  id: PricingCategoryId;
  label: string;
}

export const pricingCategories: PricingCategory[] = [
  { id: "branding", label: "Logo & Brand Identity Design" },
  { id: "website-design", label: "Business & Corporate Websites" },
  { id: "ecommerce", label: "Ecommerce Websites" },
  { id: "lms-platforms", label: "Online Course Platforms" },
  { id: "brand-website-bundles", label: "Brand + Website Bundles" },
];

export const pricingPackages: PricingPackage[] = [
  {
    id: "logo-design",
    category: "branding",
    name: "Logo Design",
    price: "₦80,000",
    bestFor: "Best for businesses that already have a clear direction but need a professional logo.",
    deliverables: [
      "Primary logo design",
      "Secondary logo variation",
      "Logo mark / icon",
      "Black & white versions",
      "Colour variations",
      "Basic colour palette",
      "Logo usage guide",
      "Final files: PNG, JPG, SVG, PDF",
    ],
    revisions: "2 revision rounds",
    support: "5 days post-delivery support",
    cta: "Start Logo Project",
  },
  {
    id: "full-brand-identity",
    category: "branding",
    name: "Full Brand Identity",
    price: "₦200,000",
    bestFor: "Best for businesses that need a complete visual identity, not just a logo.",
    deliverables: [
      "Brand discovery / consultation",
      "Creative direction",
      "Primary logo",
      "Secondary logo",
      "Logo mark / icon",
      "Complete colour system",
      "Typography system",
      "Brand visual direction",
      "Supporting graphic elements",
      "Social media profile assets",
      "Basic brand applications / mockups",
      "Full brand guidelines",
      "Final source & export files",
    ],
    revisions: "3 revision rounds",
    support: "8 days post-delivery support",
    cta: "Build My Brand",
  },
  {
    id: "website-starter",
    category: "website-design",
    name: "Website Starter",
    price: "₦350,000",
    bestFor: "Best for small businesses, professionals and service brands that need a clean, professional website.",
    deliverables: [
      "Up to 5 pages",
      "Custom website design",
      "Mobile & desktop responsive",
      "Contact / inquiry forms",
      "WhatsApp integration",
      "Social media integration",
      "Basic SEO setup",
      "Google Maps integration",
      "Basic speed optimization",
      "Deployment & SSL setup",
    ],
    revisions: "2 revision rounds",
    support: "7 days post-launch support",
    cta: "Start Your Website",
  },
  {
    id: "website-growth",
    category: "website-design",
    name: "Website Growth",
    price: "₦550,000",
    bestFor: "Best for growing businesses that need a stronger online presence and more functionality.",
    deliverables: [
      "Up to 8 pages",
      "Everything in Website Starter",
      "More advanced custom UI/UX",
      "Blog / CMS setup",
      "Newsletter integration",
      "Advanced forms",
      "Booking or appointment integration",
      "Google Analytics setup",
      "Improved SEO structure",
      "More advanced animations & interactions",
    ],
    revisions: "3 revision rounds",
    support: "14 days post-launch support",
    cta: "Build My Website",
  },
  {
    id: "custom-website",
    category: "website-design",
    name: "Custom Website",
    price: "Custom Pricing",
    bestFor: "For businesses that need something beyond a standard company website.",
    deliverables: [
      "8+ pages",
      "Fully custom layouts",
      "Advanced CMS / dynamic content",
      "CRM integrations",
      "Custom booking systems",
      "API integrations",
      "Advanced animations",
      "Custom dashboards or portals",
      "Advanced SEO structure",
      "Performance optimization",
      "Custom functionality",
      "Extended support",
    ],
    cta: "Request a Quote",
  },
  {
    id: "ecommerce-starter",
    category: "ecommerce",
    name: "Ecommerce Starter",
    price: "₦400,000",
    bestFor: "Best for small brands and businesses launching their first online store.",
    deliverables: [
      "Custom ecommerce website",
      "Up to 5 core pages",
      "Product catalogue setup",
      "Shopping cart & checkout",
      "Payment gateway integration",
      "Order management",
      "Customer accounts",
      "Basic inventory management",
      "WhatsApp integration",
      "Mobile & desktop responsive design",
      "Basic SEO setup",
      "Basic speed optimization",
      "Up to 20 products uploaded",
    ],
    revisions: "2 revision rounds",
    support: "7 days post-launch support",
    cta: "Launch Your Store",
  },
  {
    id: "ecommerce-growth",
    category: "ecommerce",
    name: "Ecommerce Growth",
    price: "₦600,000",
    bestFor: "Best for growing brands that need a more polished store and stronger selling features.",
    deliverables: [
      "Everything in Ecommerce Starter",
      "Advanced custom UI/UX",
      "Up to 50 products uploaded",
      "Product variations such as size and colour",
      "Product categories & filters",
      "Wishlist",
      "Product reviews",
      "Discount codes & promotions",
      "Advanced shipping setup",
      "Automated order emails",
      "Abandoned-cart / marketing integrations",
      "Google Analytics setup",
      "Improved SEO structure",
    ],
    revisions: "3 revision rounds",
    support: "14 days post-launch support",
    cta: "Grow Your Store",
  },
  {
    id: "custom-ecommerce",
    category: "ecommerce",
    name: "Custom Ecommerce",
    price: "Custom Pricing",
    bestFor: "For established brands or businesses that need more advanced ecommerce functionality.",
    deliverables: [
      "Fully custom ecommerce experience",
      "Large product catalogue",
      "Advanced search & filtering",
      "Multi-currency support",
      "Subscription products",
      "Multi-vendor marketplace options",
      "Custom customer dashboards",
      "CRM integrations",
      "Advanced shipping logic",
      "Third-party API integrations",
      "Advanced analytics",
      "Custom automations",
      "Advanced performance optimization",
      "Priority post-launch support",
    ],
    cta: "Request a Custom Quote",
  },
  {
    id: "lms-starter",
    category: "lms-platforms",
    name: "Online Course Platform Starter",
    price: "₦900,000",
    bestFor: "Best for educators, coaches, academies and training businesses launching their own learning platform.",
    deliverables: [
      "Custom online course website & platform",
      "Student registration & secure login",
      "Student dashboard",
      "Admin dashboard",
      "Course, module & lesson management",
      "Video lesson system",
      "Dedicated video hosting/server setup",
      "First month video hosting covered",
      "Student progress tracking",
      "Free & paid course access",
      "Payment gateway integration",
      "Automatic course access after payment",
      "Backend & database setup",
      "Required API integrations",
      "Email notifications",
      "Mobile & desktop responsive design",
      "Basic student & course analytics",
      "Admin training",
      "Deployment & domain connection",
    ],
    revisions: "2 revision rounds",
    support: "14 days post-launch support",
    thirdPartyCosts: "Third-party services such as video hosting, email services, APIs and payment gateway fees are billed separately unless stated otherwise. The Starter package includes the first month of video hosting allowance.",
    cta: "Launch Your Academy",
  },
  {
    id: "lms-growth",
    category: "lms-platforms",
    name: "Online Course Platform Growth",
    price: "₦1,300,000",
    bestFor: "Best for established academies that need more automation, student engagement and control.",
    deliverables: [
      "Everything in Online Course Platform Starter",
      "Advanced custom UI/UX",
      "Multiple courses & learning paths",
      "Advanced student progress tracking",
      "Quizzes & assessments",
      "Course completion certificates",
      "Student profile management",
      "Course search & filtering",
      "Discount codes & promotions",
      "Automated course access rules",
      "Course announcements",
      "Advanced email notifications",
      "Student activity tracking",
      "Advanced admin analytics",
      "Student performance reports",
      "Improved backend performance",
      "Additional API integrations",
    ],
    revisions: "3 revision rounds",
    support: "21 days post-launch support",
    thirdPartyCosts: "Third-party services such as video hosting, email services, APIs and payment gateway fees are billed separately unless stated otherwise. The Growth package includes the first month of video hosting allowance.",
    cta: "Scale Your Academy",
  },
  {
    id: "custom-lms",
    category: "lms-platforms",
    name: "Custom Online Course Platform",
    price: "Custom Pricing",
    bestFor: "For large academies, education startups and training companies that need a fully tailored learning ecosystem.",
    deliverables: [
      "Everything in Online Course Platform Growth",
      "Fully custom platform architecture",
      "Instructor / tutor accounts",
      "Multiple instructor management",
      "Advanced roles & permissions",
      "Live class integrations",
      "Community / discussion features",
      "Subscription & membership plans",
      "Affiliate / referral systems",
      "Advanced assessments",
      "Custom certificates",
      "Advanced student reporting",
      "CRM integrations",
      "Custom automation workflows",
      "Advanced API integrations",
      "Custom dashboards",
      "Scalable backend infrastructure",
      "Advanced security configuration",
      "Priority support",
    ],
    thirdPartyCosts: "Third-party services such as video hosting, email services, APIs and payment gateway fees are billed separately unless stated otherwise.",
    cta: "Request a Custom Quote",
  },
  {
    id: "brand-launch-package",
    category: "brand-website-bundles",
    name: "Brand Launch Package",
    price: "₦500,000",
    bestFor: "For new businesses and companies that need their brand and website built together.",
    deliverables: [
      "Brand discovery session",
      "Primary logo",
      "Secondary logo / logo mark",
      "Colour palette",
      "Typography system",
      "Brand visual direction",
      "Basic brand guidelines",
      "Social profile assets",
      "Final brand files",
      "Up to 5 website pages",
      "Custom website design",
      "Mobile & desktop responsive",
      "Brand identity applied throughout",
      "Contact / enquiry forms",
      "WhatsApp integration",
      "Social media integration",
      "Basic SEO setup",
      "Google Maps integration",
      "Deployment & domain connection",
      "Basic speed optimization",
    ],
    revisions: "3 revision rounds",
    support: "14 days post-launch support",
    notes: ["Normally ₦550,000 separately", "You save ₦50,000"],
    cta: "Launch Your Brand",
  },
  {
    id: "brand-growth-package",
    category: "brand-website-bundles",
    name: "Brand Growth Package",
    price: "₦700,000",
    bestFor: "For businesses that want a stronger identity and a more complete website.",
    deliverables: [
      "Everything in Brand Launch",
      "More developed brand visual system",
      "Additional brand applications/mockups",
      "Up to 8 website pages",
      "Advanced custom UI/UX",
      "Blog / CMS setup",
      "Newsletter integration",
      "Advanced forms",
      "Analytics setup",
      "Better SEO structure",
      "More advanced interactions/animations",
    ],
    revisions: "3 revision rounds",
    support: "21 days post-launch support",
    notes: ["Normally ₦750,000 separately", "You save ₦50,000"],
    cta: "Build Your Brand",
  },
];

export const brandingAddons = [
  "Social Media Design",
  "Packaging Design",
  "Business Cards / Stationery",
  "Brand Strategy Session",
  "Photography",
  "Content Direction",
];
