export const fallbackProjects = [
  { _id: "1", slug: "lumina-brand-identity", title: "Lumina: Brand Identity", category: "Logo & Brand Identity Design", year: "2025", description: "Full brand identity system for a Lagos-based design studio.", tags: ["Logo", "Identity", "Guidelines"] },
  { _id: "2", slug: "revive-saas-dashboard", title: "Revive: SaaS Dashboard", category: "UI/UX Design", year: "2024", description: "End-to-end product design for a health-tech startup.", tags: ["Product Design", "Figma", "Prototyping"] },
  { _id: "3", slug: "forma-agency-website", title: "Forma: Agency Website", category: "Website Design", year: "2024", description: "Award-nominated website for a creative agency.", tags: ["Webflow", "Animation", "CMS"] },
  { _id: "4", slug: "cleo-ecommerce-store", title: "Cleo: E-commerce Store", category: "Website Design", year: "2024", description: "Fashion e-commerce website focused on conversion.", tags: ["E-commerce", "Webflow", "Mobile"] },
  { _id: "5", slug: "autoflow-ai-workflow", title: "AutoFlow: AI Workflow", category: "Social Media Design", year: "2025", description: "AI-powered content and lead generation system.", tags: ["Make.com", "AI", "Automation"] },
  { _id: "6", slug: "meridian-brand-web", title: "Meridian: Brand & Web", category: "Logo & Brand Identity Design", year: "2023", description: "Brand identity and marketing site for a fintech company.", tags: ["Brand Identity", "Web", "Fintech"] },
  {
    _id: "7",
    slug: "vindicatefx-academy",
    title: "VindicateFX Academy",
    category: "Website Design",
    year: "2025",
    description: "Custom learning management system for a forex education business.",
    tags: ["LMS", "Next.js", "Payments", "Video Hosting"],
    liveUrl: "https://vindicatefxacademy.com",
    overview:
      "VindicateFX Academy is a custom learning management system built for a forex education business to bring its courses, students, payments, and learning experience into one platform. The goal was to move beyond a simple course website and create a complete platform where students could register, purchase access, watch lessons, track their progress, and manage their learning, while the academy could manage courses and students from an admin dashboard.",
    contributions: [
      "Custom LMS platform",
      "Student registration and authentication",
      "Student dashboard",
      "Admin dashboard",
      "Course and lesson management",
      "Video-based lessons",
      "Student progress tracking",
      "Free and paid course access",
      "Payment integration",
      "Automatic course access after payment",
      "Backend and database infrastructure",
      "Video hosting integration",
      "Responsive interface",
      "Deployment and production setup",
    ],
  },
];
